"""news table ga view ustunini qoshdim

Revision ID: 11b34ca2eabe
Revises: 3e9e434c5f3c
Create Date: 2025-05-05 19:34:17.228128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b34ca2eabe'
down_revision: Union[str, None] = '3e9e434c5f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('view', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'view')
    # ### end Alembic commands ###
