"""students table ga address ustunini qoshdim va emailni unique qildim

Revision ID: 3e9e434c5f3c
Revises: 648dcac9f46d
Create Date: 2025-05-05 19:27:45.391829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9e434c5f3c'
down_revision: Union[str, None] = '648dcac9f46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('address', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'students', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'address')
    # ### end Alembic commands ###
